gcp_project_id				= "labgce-cld"
gcp_service_account_key_file_path	= "/Users/dariovasq/Documents/HEIG/S4/CLD/Labo06/credentials/labgce-service-account-key.json"
gce_instance_name			= "labgce"
gce_instance_user			= "labgce"
gce_ssh_pub_key_file_path		= "/Users/dariovasq/Documents/HEIG/S4/CLD/Labo06/credentials/labgce-ssh-key.pub"